[Logger]
LogDir      = "./log/"
LogName     = "conf_agent"
LogLevel    = "INFO"
RotateWhen  = "MIDNIGHT"
BackupCount = 2
Format      = "[%D %T] [%L] [%S] %M"
StdOut      = false

[Basic]
BFECluster              = "{BFECluster}"
BFEConfDir              = "/home/work/bfe/conf"
BFEMonitorPort          = 8421
BFEReloadTimeoutMs      = 1500

ReloadIntervalMs        = 5000

ConfServer              = "http://127.0.0.1:8183"
# Token 获取参考 https://github.com/bfenetworks/dashboard/blob/develop/docs/zh-cn/user-guide/system-view/user-management.md#token%E7%AE%A1%E7%90%86
ConfTaskHeaders         = {"Authorization" = "Token {Token}"}
ConfTaskTimeoutMs       = 1500

ExtraFileServer         = "http://127.0.0.1:8183/inner-api/v1/configs/extra_files/"
# Token 获取参考 https://github.com/bfenetworks/dashboard/blob/develop/docs/zh-cn/user-guide/system-view/user-management.md#token%E7%AE%A1%E7%90%86
ExtraFileTaskHeaders    = {"Authorization" = "Token {Token}"}
ExtraFileTaskTimeoutMs  = 1500


# reloader for server_data_config files, detail see https://www.bfe-networks.net/en_us/configuration/server_data_conf/host_rule.data/
[Reloaders.server_data_conf]
CopyFiles       = ["cluster_conf.data", "host_rule.data", "name_conf.data", "route_rule.data", "vip_rule.data"]
[[Reloaders.server_data_conf.MultiKeyFileTasks]]
ConfAPI         = "/inner-api/v1/configs/tls_conf/server_data_conf"
Key2ConfFile    = {"HostTable" = "host_rule.data", "RouteTable" = "route_rule.data", "ClusterConf" = "cluster_conf.data"}

# # reloader for cluster_conf files, detail see https://www.bfe-networks.net/en_us/configuration/cluster_conf/gslb.data/
[Reloaders.cluster_conf]
BFEReloadAPI    = "/reload/gslb_data_conf"
Co